# Generated by Django 5.0.6 on 2024-05-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], null=1, verbose_name='Referral Level')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Invited User')),
                ('referral_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Referral User')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'indexes': [models.Index(fields=['referral_level'], name='referrals_r_referra_3bba89_idx')],
                'unique_together': {('invited_user', 'referral_user')},
            },
        ),
    ]
