# Generated by Django 5.0.6 on 2024-05-23 12:21

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='en', verbose_name='Interface language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Did not pass the funnel'), (2, 'Passed the funnel'), (3, 'Purchased a free product'), (4, 'Purchased a paid product')], default=1, verbose_name='Status'),
        ),
    ]
