# Generated by Django 5.0.6 on 2024-06-26 17:57

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_link',
        ),
        migrations.AddField(
            model_name='user',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=22, prefix='', verbose_name='OID'),
        ),
    ]
