version: '3.9'

name: django-ref-bot

services:
  web_app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: web_app
    ports:
      - 8000:8000
    volumes:
      - ..:/app/
    env_file:
      - ../.env
    depends_on:
      - storage_app
      - redis_app
    command: "uvicorn app.project.asgi:application --host 0.0.0.0 --workers 4 --lifespan on"