# Generated by Django 5.0.6 on 2024-05-23 15:20

import django.core.validators
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=25, verbose_name='Title RU')),
                ('title_en', models.CharField(max_length=25, verbose_name='Title EN')),
                ('description_ru', models.TextField(max_length=1000, verbose_name='Description RU')),
                ('description_en', models.TextField(max_length=1000, verbose_name='Description EN')),
                ('price', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Price')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=None, verbose_name='Referral level')),
                ('ratio', models.DecimalField(decimal_places=10, max_digits=25, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Ratio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratios', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product ratio',
                'verbose_name_plural': 'Product ratios',
                'indexes': [models.Index(fields=['referral_level', 'product_id'], name='products_pr_referra_063f43_idx')],
                'unique_together': {('product_id', 'referral_level')},
            },
        ),
    ]
